# Itamar Marom's Private Docker Registry

version: '3'
services:
#Registry
  registry:
    image: 'registry'
    restart: 'always'
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: '/certs/domain.crt'
      REGISTRY_HTTP_TLS_KEY: '/certs/domain.key'
      REGISTRY_AUTH: 'htpasswd'
      REGISTRY_AUTH_HTPASSWD_REALM: 'Registry-Realm'
      REGISTRY_AUTH_HTPASSWD_PATH: '/auth/htpasswd'
    volumes:
      - './registry-data:/var/lib/registry'
      - './auth:/auth'
      - './certs:/certs'